const $=id=>document.getElementById(id);let events=[],parsedQuestions=[],currentResults=[];
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function tab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));document.querySelectorAll('.section').forEach(x=>x.classList.toggle('active',x.id===id));}
async function isAdmin(){const {data:{user}}=await sb.auth.getUser();if(!user)return false;const {data}=await sb.from('profiles').select('role').eq('id',user.id).maybeSingle();return data?.role==='admin'}
async function boot(){if(await isAdmin()){showApp();await loadEvents()} }
function showApp(){$('loginCard').classList.add('hidden');$('adminApp').classList.remove('hidden')}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginMsg').textContent='Memproses...';const {error}=await sb.auth.signInWithPassword({email:$('adminEmail').value,password:$('adminPassword').value});if(error){$('loginMsg').textContent=error.message;return}if(!(await isAdmin())){$('loginMsg').textContent='Akun bukan admin.';await sb.auth.signOut();return}showApp();await loadEvents()});
$('logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
async function loadEvents(){const {data,error}=await sb.from('events').select('*').order('created_at',{ascending:false});if(error){alert(error.message);return}events=data||[];$('eventRows').innerHTML=events.map(e=>`<tr><td>${esc(e.event_code)}</td><td>${esc(e.event_name)}</td><td>${esc(e.event_date||'')}</td><td>${e.active?'Aktif':'Nonaktif'}</td><td><button class="secondary" onclick="editEvent('${e.id}')">Edit</button></td></tr>`).join('');for(const id of ['questionEvent','participantEvent','certificateEvent']){$(id).innerHTML=events.map(e=>`<option value="${e.id}">${esc(e.event_code)} - ${esc(e.event_name)}</option>`).join('')}await loadQuestions();await loadResults();loadCertificateForm()}
window.editEvent=id=>{const e=events.find(x=>x.id===id);if(!e)return;$('eventId').value=e.id;$('eventCodeInput').value=e.event_code;$('eventNameInput').value=e.event_name;$('workshopTitle').value=e.workshop_title||'';$('organizer').value=e.organizer||'';$('location').value=e.location||'';$('eventDate').value=e.event_date||'';$('questionCount').value=e.question_count||20;$('durationMinutes').value=e.duration_minutes||0;$('passingGrade').value=e.passing_grade||60;$('active').value=String(e.active);$('randomizeQuestions').checked=e.randomize_questions!==false;$('randomizeOptions').checked=e.randomize_options!==false;tab('events');scrollTo({top:document.body.scrollHeight,behavior:'smooth'})};
$('newEventBtn').onclick=()=>{$('eventForm').reset();$('eventId').value='';$('active').value='true';$('questionCount').value=20;$('durationMinutes').value=20;$('passingGrade').value=60};
$('eventForm').addEventListener('submit',async e=>{e.preventDefault();const row={event_code:$('eventCodeInput').value.trim().toUpperCase(),event_name:$('eventNameInput').value.trim(),workshop_title:$('workshopTitle').value.trim(),organizer:$('organizer').value.trim(),location:$('location').value.trim(),event_date:$('eventDate').value||null,question_count:+$('questionCount').value||20,duration_minutes:+$('durationMinutes').value||0,passing_grade:+$('passingGrade').value||0,active:$('active').value==='true',randomize_questions:$('randomizeQuestions').checked,randomize_options:$('randomizeOptions').checked};const id=$('eventId').value;let q=id?sb.from('events').update(row).eq('id',id):sb.from('events').insert(row);const {error}=await q;if(error)alert(error.message);else{alert('Event tersimpan.');await loadEvents()}});
function parseTxt(text){const blocks=text.split(/\n\s*#SOAL\s*\n/i).map(x=>x.trim()).filter(Boolean);return blocks.map((b,idx)=>{const lines=b.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const obj={question_type:'PG',category:null,question_text:'',options:[],correct_answers:[],weight:1};for(const line of lines){const p=line.indexOf('=');if(p<0)continue;const k=line.slice(0,p).trim().toUpperCase(),v=line.slice(p+1).trim();if(k==='TYPE')obj.question_type=v.toUpperCase();else if(k==='CATEGORY')obj.category=v;else if(k==='PERTANYAAN')obj.question_text=v;else if(['A','B','C','D','E'].includes(k))obj.options.push({key:k,text:v});else if(k==='JAWABAN')obj.correct_answers=v.split('|').map(x=>x.trim());else if(k==='BOBOT')obj.weight=Number(v)||1}if(obj.question_type==='TF'&&obj.options.length===0)obj.options=[{key:'TRUE',text:'Benar'},{key:'FALSE',text:'Salah'}];if(!obj.question_text)throw new Error(`Soal blok ${idx+1} tidak memiliki PERTANYAAN`);return obj})}
$('parseQuestionsBtn').onclick=async()=>{const f=$('questionFile').files[0];if(!f){alert('Pilih file TXT.');return}try{parsedQuestions=parseTxt(await f.text());$('questionPreview').innerHTML=`<div class="status">Terbaca <b>${parsedQuestions.length}</b> soal.</div>`+parsedQuestions.slice(0,5).map((q,i)=>`<div class="question"><b>${i+1}. ${esc(q.question_text)}</b><div class="small">${q.question_type} • Kunci: ${esc(q.correct_answers.join('|'))}</div></div>`).join('');$('importQuestionsBtn').disabled=!parsedQuestions.length}catch(e){alert(e.message)}};
$('importQuestionsBtn').onclick=async()=>{const event_id=$('questionEvent').value;if(!event_id||!parsedQuestions.length)return;if(!confirm(`Import ${parsedQuestions.length} soal ke event ini?`))return;const rows=parsedQuestions.map(q=>({...q,event_id}));for(let i=0;i<rows.length;i+=100){const {error}=await sb.from('questions').insert(rows.slice(i,i+100));if(error){alert(error.message);return}}alert('Soal berhasil diimport.');await loadQuestions()};
async function loadQuestions(){const event_id=$('questionEvent').value;if(!event_id){$('questionRows').innerHTML='';return}const {data,error}=await sb.from('questions').select('question_type,category,question_text,weight').eq('event_id',event_id).eq('active',true).limit(500);if(error)return;$('questionStats').textContent=`Total ${data.length} soal`;$('questionRows').innerHTML=data.map(q=>`<tr><td>${q.question_type}</td><td>${esc(q.category||'-')}</td><td>${esc(q.question_text)}</td><td>${q.weight}</td></tr>`).join('')}
$('questionEvent').onchange=loadQuestions;
async function loadResults(){const event_id=$('participantEvent').value;if(!event_id){$('resultRows').innerHTML='';return}const {data,error}=await sb.from('admin_results').select('*').eq('event_id',event_id).order('submitted_at',{ascending:false});if(error){console.warn(error);return}currentResults=data||[];const scores=currentResults.filter(x=>x.score!=null).map(x=>Number(x.score));const avg=scores.length?scores.reduce((a,b)=>a+b,0)/scores.length:0;$('resultStats').innerHTML=`<div class="status"><b>${currentResults.length}</b><br>Peserta</div><div class="status"><b>${scores.length}</b><br>Selesai</div><div class="status"><b>${avg.toFixed(1)}</b><br>Rata-rata</div>`;$('resultRows').innerHTML=currentResults.map(r=>`<tr><td>${esc(r.participant_name)}</td><td>${esc(r.school||'-')}</td><td>${r.score==null?'-':Math.round(r.score)}</td><td>${r.correct_count??'-'}</td><td>${esc(r.certificate_number||'-')}</td><td>${esc(r.submitted_at||'-')}</td></tr>`).join('')}
$('participantEvent').onchange=loadResults;$('refreshResults').onclick=loadResults;$('exportCsv').onclick=()=>{if(!currentResults.length)return;const cols=['participant_name','school','class_name','email','score','correct_count','incorrect_count','certificate_number','submitted_at'];const csv=[cols.join(','),...currentResults.map(r=>cols.map(c=>`"${String(r[c]??'').replaceAll('"','""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='hasil-posttest.csv';a.click()};
function loadCertificateForm(){const id=$('certificateEvent').value,e=events.find(x=>x.id===id);if(!e)return;$('certificateTitle').value=e.certificate_title||'SERTIFIKAT PENGHARGAAN';$('recipientLabel').value=e.recipient_label||'Diberikan Kepada';$('participantRole').value=e.participant_role||'PESERTA';$('signerName').value=e.signer_name||'';$('signerPosition').value=e.signer_position||'';$('certificateNarrative').value=e.certificate_narrative||'Menyatakan bahwa yang bersangkutan telah mengikuti workshop "{WORKSHOP}" yang diselenggarakan oleh {ORGANIZER} di {LOCATION} pada tanggal {DATE}.';$('layoutJson').value=e.certificate_layout?JSON.stringify(e.certificate_layout,null,2):'';renderEventQr(e)}
$('certificateEvent').onchange=loadCertificateForm;
async function uploadAsset(file,eventCode,prefix){if(!file)return null;const ext=file.name.split('.').pop();const path=`${eventCode}/${prefix}-${Date.now()}.${ext}`;const {error}=await sb.storage.from('certificate-assets').upload(path,file,{upsert:true});if(error)throw error;return sb.storage.from('certificate-assets').getPublicUrl(path).data.publicUrl}
$('saveCertificate').onclick=async()=>{const id=$('certificateEvent').value,e=events.find(x=>x.id===id);if(!e)return;try{const templateUrl=await uploadAsset($('templateFile').files[0],e.event_code,'template');const signatureUrl=await uploadAsset($('signatureFile').files[0],e.event_code,'signature');let layout=null;if($('layoutJson').value.trim())layout=JSON.parse($('layoutJson').value);const row={certificate_title:$('certificateTitle').value.trim(),recipient_label:$('recipientLabel').value.trim(),participant_role:$('participantRole').value.trim(),signer_name:$('signerName').value.trim(),signer_position:$('signerPosition').value.trim(),certificate_narrative:$('certificateNarrative').value.trim(),certificate_layout:layout};if(templateUrl)row.certificate_template_url=templateUrl;if(signatureUrl)row.signature_url=signatureUrl;const {error}=await sb.from('events').update(row).eq('id',id);if(error)throw error;alert('Setting sertifikat tersimpan.');await loadEvents()}catch(err){alert(err.message)}};
$('previewCertificate').onclick=async()=>{const id=$('certificateEvent').value,e=events.find(x=>x.id===id);if(!e)return;let layout;try{layout=$('layoutJson').value.trim()?JSON.parse($('layoutJson').value):undefined}catch{alert('Layout JSON tidak valid');return}const data={templateUrl:e.certificate_template_url||'assets/template_upj_blue.png',participantName:'NAMA PESERTA CONTOH',workshopTitle:e.workshop_title||e.event_name,certificateTitle:$('certificateTitle').value,recipientLabel:$('recipientLabel').value,roleLabel:'Sebagai',participantRole:$('participantRole').value,narrative:$('certificateNarrative').value.replaceAll('{WORKSHOP}',e.workshop_title||'').replaceAll('{ORGANIZER}',e.organizer||'').replaceAll('{LOCATION}',e.location||'').replaceAll('{DATE}',e.event_date||''),signerName:$('signerName').value,signerPosition:$('signerPosition').value,signatureUrl:e.signature_url,certificateNumber:`CERT-${e.event_code}-0001`,verifyUrl:location.origin+location.pathname.replace('admin.html','verify.html')+'?code=DEMO',layout};await CertificateEngine.renderCertificate($('certificateCanvas'),data)};
function renderEventQr(e){const q=$('eventQr');q.innerHTML='';const url=new URL('index.html',location.href);url.searchParams.set('event',e.event_code);new QRCode(q,{text:url.href,width:180,height:180});$('eventLink').textContent=url.href}
boot();
