let currentEvent=null,currentAttempt=null,currentQuestions=[];let timerHandle=null,secondsLeft=0;
const $=id=>document.getElementById(id);
function msg(t){$('message').textContent=t;$('message').classList.remove('hidden')}
async function init(){const p=new URLSearchParams(location.search);const code=(p.get('event')||APP_CONFIG.DEFAULT_EVENT_CODE).trim().toUpperCase();$('eventCode').textContent=code;const {data,error}=await sb.rpc('get_event',{p_event_code:code});if(error||!data){msg('Event tidak ditemukan / belum aktif.');return}currentEvent=data;$('eventName').textContent=data.event_name;$('eventMeta').textContent=`${data.organizer||''} • ${data.location||''} • ${data.event_date||''}`;$('identityCard').classList.remove('hidden')}
async function startTest(e){e.preventDefault();const payload={p_event_code:currentEvent.event_code,p_name:$('name').value.trim(),p_school:$('school').value.trim(),p_class_name:$('className').value.trim(),p_email:$('email').value.trim(),p_phone:$('phone').value.trim()};if(!payload.p_name||!payload.p_school){msg('Nama dan asal sekolah wajib diisi.');return}const {data,error}=await sb.rpc('start_test',payload);if(error){msg(error.message);return}currentAttempt=data.attempt_id;currentQuestions=data.questions||[];$('identityCard').classList.add('hidden');$('testCard').classList.remove('hidden');renderQuestions();if(data.duration_minutes>0){secondsLeft=data.duration_minutes*60;timerHandle=setInterval(()=>{secondsLeft--;$('timer').textContent=`${Math.floor(secondsLeft/60)}:${String(secondsLeft%60).padStart(2,'0')}`;if(secondsLeft<=0){clearInterval(timerHandle);submitTest()}},1000)}}
function renderQuestions(){const wrap=$('questions');wrap.innerHTML='';currentQuestions.forEach((q,i)=>{const div=document.createElement('div');div.className='question';let html=`<b>${i+1}. ${escapeHtml(q.question_text)}</b><div class="small muted">${q.question_type}${q.category?` • ${escapeHtml(q.category)}`:''}</div>`;if(q.question_type==='PG'||q.question_type==='TF'){let opts=[...(q.options||[])];if(currentEvent.randomize_options)opts.sort(()=>Math.random()-.5);for(const o of opts){html+=`<label class="option"><input type="radio" name="q_${q.id}" value="${escapeHtml(o.key)}"> <b>${escapeHtml(o.key)}.</b> ${escapeHtml(o.text)}</label>`}}else{html+=`<input type="text" name="q_${q.id}" placeholder="Jawaban singkat">`}div.innerHTML=html;wrap.appendChild(div)});$('progressText').textContent=`0 / ${currentQuestions.length}`;wrap.addEventListener('change',updateProgress);wrap.addEventListener('input',updateProgress)}
function updateProgress(){let n=0;for(const q of currentQuestions){const els=document.getElementsByName(`q_${q.id}`);if(q.question_type==='SHORT'){if(els[0]?.value.trim())n++}else if([...els].some(e=>e.checked))n++}$('progressText').textContent=`${n} / ${currentQuestions.length}`;$('progressBar').style.width=`${currentQuestions.length?100*n/currentQuestions.length:0}%`}
async function submitTest(){if(!currentAttempt)return;if(timerHandle)clearInterval(timerHandle);const answers={};for(const q of currentQuestions){const els=document.getElementsByName(`q_${q.id}`);if(q.question_type==='SHORT')answers[q.id]=els[0]?.value.trim()||'';else answers[q.id]=[...els].find(e=>e.checked)?.value||''}$('submitBtn').disabled=true;const {data,error}=await sb.rpc('submit_test',{p_attempt_id:currentAttempt,p_answers:answers});if(error){msg(error.message);$('submitBtn').disabled=false;return}$('testCard').classList.add('hidden');$('resultCard').classList.remove('hidden');$('score').textContent=Math.round(data.score);$('resultStatus').textContent=data.passed?'LULUS':'SELESAI';$('resultStatus').className=data.passed?'ok':'danger';$('correctInfo').textContent=`Benar ${data.correct_count} dari ${data.total_questions}`;await showCertificate(data)}
async function showCertificate(res){const verifyUrl=new URL('verify.html',location.href);verifyUrl.searchParams.set('code',res.verification_code);const narrative=(res.certificate_narrative||'Menyatakan bahwa yang bersangkutan telah mengikuti workshop "{WORKSHOP}" yang diselenggarakan di {LOCATION} pada tanggal {DATE}.').replaceAll('{WORKSHOP}',res.workshop_title||'').replaceAll('{LOCATION}',res.location||'').replaceAll('{DATE}',res.event_date||'').replaceAll('{ORGANIZER}',res.organizer||'');const data={templateUrl:res.certificate_template_url||'assets/template_upj_blue.png',participantName:res.participant_name,workshopTitle:res.workshop_title,certificateTitle:res.certificate_title,recipientLabel:res.recipient_label,roleLabel:'Sebagai',participantRole:res.participant_role,narrative,signerName:res.signer_name,signerPosition:res.signer_position,signatureUrl:res.signature_url,certificateNumber:res.certificate_number,verifyUrl:verifyUrl.href,layout:res.certificate_layout||undefined};await CertificateEngine.renderCertificate($('certificateCanvas'),data);$('downloadBtn').onclick=()=>CertificateEngine.downloadPdf($('certificateCanvas'),`${res.certificate_number}-${res.participant_name}.pdf`)}
function escapeHtml(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('identityForm').addEventListener('submit',startTest);$('submitBtn').addEventListener('click',()=>{if(confirm('Yakin ingin submit post-test?'))submitTest()});init();
