let currentEvent=null,currentEventCode='',currentAttempt=null,currentQuestions=[],postTimer=null,postSubmitting=false;let quizPlayerId=null,quizSessionId=null,quizPoll=null,quizChannel=null,lastQuizQuestionId=null,lastViolationAt=0,quizSecurityActive=false,quizLastState=null;
const $=id=>document.getElementById(id);function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function msg(t){$('message').textContent=t;$('message').classList.remove('hidden')}function hideMsg(){$('message').classList.add('hidden')}function showOnly(id){['identityCard','posttestCard','quizLobby','quizPlay','quizReveal','quizFinished','resultCard'].forEach(x=>$(x).classList.toggle('hidden',x!==id))}
function modeLabel(m){return m==='QUIZ'?'QUIZ MODE':m==='CERTIFICATE'?'CERTIFICATE ONLY':'POST-TEST MODE'}
async function init(){const p=new URLSearchParams(location.search);currentEventCode=(p.get('event')||APP_CONFIG.DEFAULT_EVENT_CODE).trim().toUpperCase();$('eventCode').textContent=currentEventCode;const {data,error}=await sb.rpc('get_event',{p_event_code:currentEventCode});if(error||!data)return msg('Event tidak ditemukan / belum aktif.');currentEvent=data;$('eventName').textContent=data.event_name;$('eventMeta').textContent=`${data.organizer||''} • ${data.location||''} • ${CertificateEngine.formatDateId(data.event_date)||''}`;$('modeBadge').textContent=modeLabel(data.event_mode);if(data.event_mode==='POSTTEST'&&await resumePostTest())return;if(data.event_mode==='QUIZ'&&await resumeQuiz())return;prepareIdentity()}
function prepareIdentity(){showOnly('identityCard');if(currentEvent.event_mode==='QUIZ'){$('identityTitle').textContent='Masuk Quiz';$('identitySubmit').textContent=currentEvent.quiz_fullscreen_required?'Masuk Quiz & Aktifkan Fullscreen':'Masuk Quiz';$('phoneWrap').classList.add('hidden');$('classWrap').classList.add('hidden')}else if(currentEvent.event_mode==='CERTIFICATE'){$('identityTitle').textContent='Data Sertifikat';$('identitySubmit').textContent='Generate Sertifikat'}else{$('identityTitle').textContent='Identitas Peserta';$('identitySubmit').textContent='Mulai Post-Test'}}
$('identityForm').addEventListener('submit',async e=>{e.preventDefault();hideMsg();if(!$('name').value.trim()||!$('school').value.trim())return msg('Nama dan asal sekolah wajib diisi.');if(currentEvent.event_mode==='QUIZ')return joinQuiz();if(currentEvent.event_mode==='CERTIFICATE')return issueCertificateOnly();return startPostTest()});
// POST TEST
function postKey(){return `posttest_attempt_${currentEventCode}`}function answerKey(){return `posttest_answers_${currentAttempt}`}function collectAnswers(){const a={};for(const q of currentQuestions){const els=document.getElementsByName(`q_${q.id}`);a[q.id]=q.question_type==='SHORT'?(els[0]?.value.trim()||''):([ ...els].find(e=>e.checked)?.value||'')}return a}function savePost(){if(currentAttempt){localStorage.setItem(postKey(),currentAttempt);localStorage.setItem(answerKey(),JSON.stringify(collectAnswers()))}}
async function startPostTest(){const {data,error}=await sb.rpc('start_test',{p_event_code:currentEventCode,p_name:$('name').value.trim(),p_school:$('school').value.trim(),p_class_name:$('className').value.trim(),p_email:$('email').value.trim(),p_phone:$('phone').value.trim()});if(error)return msg(error.message);currentAttempt=data.attempt_id;currentQuestions=data.questions||[];savePost();showOnly('posttestCard');renderPostQuestions();const {data:r}=await sb.rpc('resume_test',{p_attempt_id:currentAttempt});startPostTimer(r?.remaining_seconds??((data.duration_minutes||0)*60))}
async function resumePostTest(){const aid=localStorage.getItem(postKey());if(!aid)return false;const {data,error}=await sb.rpc('resume_test',{p_attempt_id:aid});if(error||!data||data.status==='submitted'){localStorage.removeItem(postKey());return false}currentAttempt=aid;currentQuestions=data.questions||[];showOnly('posttestCard');renderPostQuestions();try{const saved=JSON.parse(localStorage.getItem(answerKey())||'{}');for(const q of currentQuestions){const els=document.getElementsByName(`q_${q.id}`);if(q.question_type==='SHORT'){if(els[0])els[0].value=saved[q.id]||''}else[...els].forEach(x=>x.checked=x.value===saved[q.id])}}catch{}updateProgress();startPostTimer(data.remaining_seconds);msg('Post-test dilanjutkan. Timer tidak direset.');return true}
function renderPostQuestions(){$('questions').innerHTML='';currentQuestions.forEach((q,i)=>{const d=document.createElement('div');d.className='question';let h=`<b>${i+1}. ${esc(q.question_text)}</b><div class="small muted">${q.question_type}</div>`;if(q.question_type==='SHORT')h+=`<input name="q_${q.id}" type="text" placeholder="Jawaban singkat">`;else{let opts=[...(q.options||[])];if(currentEvent.randomize_options)opts.sort(()=>Math.random()-.5);h+=opts.map(o=>`<label class="option"><input type="radio" name="q_${q.id}" value="${esc(o.key)}"> <b>${esc(o.key)}.</b> ${esc(o.text)}</label>`).join('')}d.innerHTML=h;$('questions').appendChild(d)});updateProgress()}
function updateProgress(){let n=0;for(const q of currentQuestions){const els=document.getElementsByName(`q_${q.id}`);if(q.question_type==='SHORT'?els[0]?.value.trim():[...els].some(e=>e.checked))n++}$('progressText').textContent=`${n} / ${currentQuestions.length}`;$('progressBar').style.width=`${currentQuestions.length?100*n/currentQuestions.length:0}%`;savePost()}$('questions').addEventListener('change',updateProgress);$('questions').addEventListener('input',updateProgress);
function startPostTimer(sec){if(postTimer)clearInterval(postTimer);if(currentEvent.duration_minutes<=0){$('timer').textContent='Tanpa timer';return}let left=Math.max(0,+sec||0);const tick=()=>{$('timer').textContent=`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}`;if(left<=0){clearInterval(postTimer);postTimer=null;submitPost(true);return}left--};tick();postTimer=setInterval(tick,1000)}
$('submitBtn').onclick=()=>{if(confirm('Yakin ingin submit post-test?'))submitPost(false)};async function submitPost(auto=false){if(postSubmitting)return;postSubmitting=true;if(postTimer)clearInterval(postTimer);const {data,error}=await sb.rpc('submit_test',{p_attempt_id:currentAttempt,p_answers:collectAnswers()});if(error){postSubmitting=false;return msg(error.message)}localStorage.removeItem(postKey());localStorage.removeItem(answerKey());showResultCertificate(data,true)}
// CERTIFICATE ONLY
async function issueCertificateOnly(){const btn=$('identitySubmit');btn.disabled=true;btn.textContent='Membuat sertifikat...';const {data,error}=await sb.rpc('issue_certificate_only',{p_event_code:currentEventCode,p_name:$('name').value.trim(),p_school:$('school').value.trim(),p_class_name:$('className').value.trim(),p_email:$('email').value.trim(),p_phone:$('phone').value.trim()});btn.disabled=false;if(error){btn.textContent='Generate Sertifikat';return msg(error.message)}showResultCertificate(data,false)}
async function showResultCertificate(res,showScore){showOnly('resultCard');$('resultTitle').textContent=showScore?'Post-Test Selesai':'Sertifikat Berhasil Dibuat';$('scoreWrap').classList.toggle('hidden',!showScore);if(showScore){$('score').textContent=Math.round(res.score);$('resultStatus').textContent=res.passed?'LULUS':'SELESAI';$('resultStatus').className=res.passed?'ok':'danger';$('correctInfo').textContent=`Benar ${res.correct_count} dari ${res.total_questions}`}const verify=new URL('verify.html',location.href);verify.searchParams.set('code',res.verification_code);const date=CertificateEngine.formatDateId(res.event_date);const narrative=(res.certificate_narrative||'').replaceAll('{WORKSHOP}',res.workshop_title||'').replaceAll('{ORGANIZER}',res.organizer||'').replaceAll('{LOCATION}',res.location||'').replaceAll('{DATE}',date);const d={templateUrl:res.certificate_template_url||'assets/template_upj_blue.png',participantName:res.participant_name,workshopTitle:res.workshop_title,certificateTitle:res.certificate_title,recipientLabel:res.recipient_label,roleLabel:'Sebagai',participantRole:res.participant_role,narrative,signerName:res.signer_name,signerPosition:res.signer_position,signatureUrl:res.signature_url,certificateNumber:res.certificate_number,verifyUrl:verify.href,layout:res.certificate_layout||undefined};await CertificateEngine.renderCertificate($('certificateCanvas'),d);$('downloadBtn').onclick=()=>CertificateEngine.downloadPdf($('certificateCanvas'),`${res.certificate_number}-${res.participant_name}.pdf`)}
// QUIZ MODE
function quizKey(){return `quiz_player_${currentEventCode}`}
async function requestFullscreen(){if(!currentEvent.quiz_fullscreen_required)return true;const el=document.documentElement;if(document.fullscreenElement)return true;if(el.requestFullscreen){try{await el.requestFullscreen();return true}catch{msg('Fullscreen tidak dapat diaktifkan otomatis pada browser ini. Quiz tetap berjalan dan keluar fullscreen akan dicatat bila API tersedia.');return false}}msg('Browser ini tidak mendukung Fullscreen API.');return false}
async function joinQuiz(){await requestFullscreen();const {data,error}=await sb.rpc('quiz_join',{p_event_code:currentEventCode,p_name:$('name').value.trim(),p_school:$('school').value.trim(),p_email:$('email').value.trim()});if(error)return msg(error.message);quizPlayerId=data.player_id;quizSessionId=data.session_id;localStorage.setItem(quizKey(),JSON.stringify({player_id:quizPlayerId,session_id:quizSessionId}));$('quizPlayerName').textContent=$('name').value.trim();activateQuizSecurity();subscribeQuiz();startQuizPolling();await refreshQuizState()}
async function resumeQuiz(){let s;try{s=JSON.parse(localStorage.getItem(quizKey())||'null')}catch{}if(!s?.player_id)return false;const {data,error}=await sb.rpc('quiz_get_player_state',{p_player_id:s.player_id});if(error||!data||['finished','kicked'].includes(data.player_status)){localStorage.removeItem(quizKey());return false}quizPlayerId=s.player_id;quizSessionId=s.session_id;$('quizPlayerName').textContent=data.player_name||'';activateQuizSecurity();subscribeQuiz();startQuizPolling();renderQuizState(data);return true}
async function subscribeQuiz(){if(quizChannel)await sb.removeChannel(quizChannel);quizChannel=sb.channel('player-'+quizSessionId).on('postgres_changes',{event:'*',schema:'public',table:'quiz_sessions',filter:`id=eq.${quizSessionId}`},refreshQuizState).on('postgres_changes',{event:'*',schema:'public',table:'quiz_players',filter:`id=eq.${quizPlayerId}`},refreshQuizState).subscribe()}
function startQuizPolling(){if(quizPoll)clearInterval(quizPoll);quizPoll=setInterval(refreshQuizState,1200)}async function refreshQuizState(){if(!quizPlayerId)return;const {data,error}=await sb.rpc('quiz_get_player_state',{p_player_id:quizPlayerId});if(error||!data)return;quizLastState=data;renderQuizState(data)}
let clientQuizTimer=null;function renderQuizState(s){$('quizLobbyCount').textContent=s.player_count||0;$('quizScore').textContent=s.score||0;if(s.player_status==='kicked'){showOnly('quizFinished');$('finalRank').textContent='KICKED';$('finalScore').textContent='Dikeluarkan karena pelanggaran';return}if(s.status==='lobby'){showOnly('quizLobby');return}if(s.status==='question'){showOnly('quizPlay');$('quizQuestionNo').textContent=`${s.current_question_no}/${s.total_questions}`;$('quizQuestionText').textContent=s.question?.question_text||'';if(lastQuizQuestionId!==s.question?.id){lastQuizQuestionId=s.question?.id;renderQuizOptions(s.question,s.has_answered);QuizAudio.start(s.question_seconds||20)}else if(s.has_answered){[...$('quizOptions').querySelectorAll('button')].forEach(b=>b.disabled=true);$('quizAnswered').classList.remove('hidden')}startClientQuizClock(s.question_ends_at,s.question_seconds);return}QuizAudio.stop();if(s.status==='reveal'){showOnly('quizReveal');const correct=s.last_answer_correct===true;$('quizRevealIcon').textContent=correct?'✓':'✕';$('quizRevealTitle').textContent=correct?'Benar!':'Belum tepat';$('quizPoints').textContent=`+${s.last_points||0}`;$('quizRevealScore').textContent=s.score||0;$('quizRank').textContent=s.rank?`#${s.rank}`:'-';$('quizMiniLeaderboard').innerHTML=(s.leaderboard||[]).slice(0,5).map((p,i)=>`<li>#${i+1} ${esc(p.name)} — ${p.score}</li>`).join('');return}if(s.status==='finished'){showOnly('quizFinished');$('finalRank').textContent=s.rank?`#${s.rank}`:'#-';$('finalScore').textContent=`${s.score||0} poin`;$('finalLeaderboard').innerHTML=(s.leaderboard||[]).slice(0,10).map((p,i)=>`<li>#${i+1} ${esc(p.name)} — ${p.score}</li>`).join('');localStorage.removeItem(quizKey());deactivateQuizSecurity();if(quizPoll)clearInterval(quizPoll)}}
function renderQuizOptions(q,answered){let opts=[...(q?.options||[])];if(currentEvent.randomize_options)opts.sort(()=>Math.random()-.5);$('quizOptions').innerHTML=opts.map(o=>`<button class="quiz-option-btn" data-answer="${esc(o.key)}" ${answered?'disabled':''}><b>${esc(o.key)}.</b> ${esc(o.text)}</button>`).join('');$('quizAnswered').classList.toggle('hidden',!answered);$('quizOptions').querySelectorAll('button').forEach(b=>b.onclick=()=>submitQuizAnswer(q.id,b.dataset.answer))}
async function submitQuizAnswer(qid,ans){[...$('quizOptions').querySelectorAll('button')].forEach(b=>b.disabled=true);$('quizAnswered').classList.remove('hidden');const {error}=await sb.rpc('quiz_submit_answer',{p_player_id:quizPlayerId,p_question_id:qid,p_answer:ans});if(error)msg(error.message);await refreshQuizState()}
function startClientQuizClock(endIso,total){if(clientQuizTimer)clearInterval(clientQuizTimer);const end=new Date(endIso).getTime();const tick=()=>{const ms=Math.max(0,end-Date.now()),sec=Math.ceil(ms/1000);$('quizClock').textContent=sec;QuizAudio.intensity(total?1-ms/(total*1000):1);if(ms<=0){clearInterval(clientQuizTimer);clientQuizTimer=null}};tick();clientQuizTimer=setInterval(tick,200)}
// WebAudio synthesized timer music: no external copyrighted audio file.
const QuizAudio={ctx:null,gain:null,beat:null,level:0,enabled:false,start(total){if(!currentEvent.quiz_music_enabled)return;try{this.ctx=this.ctx||new (window.AudioContext||window.webkitAudioContext)();this.gain=this.gain||this.ctx.createGain();this.gain.connect(this.ctx.destination);this.gain.gain.value=.035;this.enabled=true;this.schedule()}catch{}},schedule(){if(!this.enabled)return;clearTimeout(this.beat);const ctx=this.ctx,osc=ctx.createOscillator(),g=ctx.createGain();osc.frequency.value=this.level>.75?660:440;osc.type='sine';g.gain.setValueAtTime(.0001,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.08+this.level*.08,ctx.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.09);osc.connect(g);g.connect(this.gain);osc.start();osc.stop(ctx.currentTime+.1);this.gain.gain.value=.03+this.level*.07;this.beat=setTimeout(()=>this.schedule(),Math.max(180,520-this.level*330))},intensity(v){this.level=Math.min(1,Math.max(0,v))},stop(){this.enabled=false;clearTimeout(this.beat);if(this.gain)this.gain.gain.value=0}};
// Security only for QUIZ
function activateQuizSecurity(){if(!currentEvent.quiz_security_enabled)return;quizSecurityActive=true;if(currentEvent.quiz_block_selection)document.body.classList.add('quiz-secure');document.addEventListener('copy',blockClipboard,true);document.addEventListener('cut',blockClipboard,true);document.addEventListener('paste',blockClipboard,true);document.addEventListener('contextmenu',blockContext,true);document.addEventListener('visibilitychange',onVisibility,true);document.addEventListener('fullscreenchange',onFullscreen,true)}function deactivateQuizSecurity(){quizSecurityActive=false;document.body.classList.remove('quiz-secure');document.removeEventListener('copy',blockClipboard,true);document.removeEventListener('cut',blockClipboard,true);document.removeEventListener('paste',blockClipboard,true);document.removeEventListener('contextmenu',blockContext,true);document.removeEventListener('visibilitychange',onVisibility,true);document.removeEventListener('fullscreenchange',onFullscreen,true)}function blockClipboard(e){if(quizSecurityActive&&currentEvent.quiz_block_clipboard)e.preventDefault()}function blockContext(e){if(quizSecurityActive&&currentEvent.quiz_block_right_click)e.preventDefault()}function onVisibility(){if(quizSecurityActive&&currentEvent.quiz_detect_tab_switch&&document.hidden)reportViolation('TAB_OR_APP_SWITCH')}function onFullscreen(){if(quizSecurityActive&&currentEvent.quiz_fullscreen_required&&!document.fullscreenElement)reportViolation('FULLSCREEN_EXIT')}
async function reportViolation(type){const now=Date.now();if(now-lastViolationAt<1800)return;lastViolationAt=now;const {data,error}=await sb.rpc('quiz_report_violation',{p_player_id:quizPlayerId,p_violation_type:type,p_details:{url:location.href}});if(error)return;const text=`Pelanggaran ${data.violations}/${data.max_violations}: ${type}${data.action_taken?` — ${data.action_taken}`:''}`;$('securityText').textContent=text;$('securityWarning').classList.remove('hidden');setTimeout(()=>$('securityWarning').classList.add('hidden'),4500);if(['KICK','AUTO_FINISH'].includes(data.action_taken))refreshQuizState();else if(currentEvent.quiz_fullscreen_required&&!document.fullscreenElement)setTimeout(requestFullscreen,200)}
init();
